### Login
POST http://localhost:11500/Login
AppVersion: 1.0.0
MasterDataVersion: 20250725
Content-Type: application/json

{
  "AccountUid": 1,
  "Token": "test-login-token-1"
}

### Logout
POST http://localhost:11500/Logout
AppVersion: 1.0.0
MasterDataVersion: 20250725
Content-Type: application/json

{
  "Token": "test-login-token-1"
}
# Content-Type: application/json

# {
#   "AccountId": 12345
# }