### Get Mail List
POST http://localhost:11500/growth/upgrade-ability/
AppVersion: 1.0.0
MasterDataVersion: 20250725
Token: 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b
Content-Type: application/json

{
  "AbilityId": 1,
  "Delta": 20
}