POST http://localhost:11500/Login
Content-Type: application/json
AppVersion: 1.0.0
MasterDataVersion: 20250725

{
  "PlatformId":1,
  "PlatformToken":"6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b",
  "PlatformName":"hive"
}

### Logout

POST http://localhost:11500/Logout
AppVersion: 1.0.0
MasterDataVersion: 20250725
Content-Type: application/json
token: 6b87zbgagtg6dz3etcuhix4ye
uid: 1

{
  "AccountId":1,
  "GameServerToken":"6b87zbgagtg6dz3etcuhix4ye"
}

###
