### Login
POST http://localhost:11500/Login
AppVersion: 1.0.0
MasterDataVersion: 20250725
Content-Type: application/json

{
  "PlayerUid": 1,
  "Token": "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b"
}

### Logout
POST http://localhost:11500/Logout
AppVersion: 1.0.0
MasterDataVersion: 20250725
Content-Type: application/json

{
  "Token": "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b"
}