@HiveServer_HostAddress = http://localhost:11501
### Create Hive Account
POST http://localhost:11501/CreateHiveAccount
Content-Type: application/json

{
  "Email": "testuser@example.com",
  "Password": "testpassword"
}

### Login Hive
POST http://localhost:11501/LoginHive
Content-Type: application/json

{
  "Email": "testuser@example.com",
  "Password": "testpassword"
}

### Verify Token
POST http://localhost:11501/VerifyToken
Content-Type: application/json

{
  "PlayerId": 0,
  "HiveToken": "5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9"
}
