@HiveServer_HostAddress = http://localhost:11501
### Create Hive Account
POST http://localhost:11501/CreateHiveAccount
Content-Type: application/json

{
  "Email": "testuser@example.com",
  "Password": "testpassword"
}

### Login Hive
POST http://localhost:11501/LoginHive
Content-Type: application/json

{
  "Email": "testuser@example.com",
  "Password": "testpassword"
}

### Verify Token
POST http://localhost:11501/VerifyToken
Content-Type: application/json

{
  "AccountId": 1,
  "HiveToken": "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b"
}

### Add Sample Category
POST http://localhost:11501/Test/AddSample
Content-Type: application/json

{}


### find Category by Id
POST http://localhost:11501/Test/FindSample
Content-Type: application/json

{}